<?php
// $Id: $

/********** The rideshare view *****************************************/


// Oy.  Lots of errors in a randomish way when this module loaded before
// 	that one.  Do we need to do this here, or in .install ?
module_load_include('inc', 'node', 'node.pages');
module_load_include('inc', 'verdant_share', 'verdant_share_flags'); 


function verdant_share_enable() {
	// not sure why content creation didn't work in install.  It worked recopied
	// 	into enable.  That seems hackish but error-free, yes/no?

	if ( ! variable_get('verdant_share_fully_installed', null) ) {
		$filename = drupal_get_path('module','verdant_share') . "/verdant_ride_cck.inc";

		$content_type = file_get_contents($filename);

		// Build form state
		$form_state = array(
			'values' => array(
				'type_name' => '<create>',
				'macro' => $content_type,
			),
		);
		// content_copy is a module for importing & exporting CCK types
		drupal_execute("content_copy_import_form", $form_state);
		content_clear_type_cache();
		drupal_set_message("Attempted to create the cck type 'Share the Ride' while enabling Verdant Share module.");

		variable_set('verdant_share_fully_installed', 1);
	}
}


/**********  Most code below here focuses on the Share profile *********/

// Create a Content Profile block for roomshare
/**
 * Implementation of hook_block()
 */
function verdant_share_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
		case 'list':
			// why didn't using [0] work? oy.
			$blocks[0] = array(
				'info'       => t('Ride Share Profile via Verdant, Block'),
				'status'     => TRUE,
				'weight'     => 0,
				'visibility' => 1,
				'pages'      => 'share/rid*',  // both ride and ride/xxx
			);

			/* For published module, non-ride options removed, but keeping 
				indexed-block style as if there was more than one block.*/
			$blocks[1]['info'] = t('Ride Share Profile Block');
			$blocks[1]['pages'] = "share/ride/*\nshare/ride";
			$blocks[1]['visibility'] = 1; // show only on listed pages
			// status and region should be set by user, but must be set.
			// $blocks[2]['info'] = t('Flight Match Profile Block');
			// $blocks[3]['info'] = t('Room Match Profile Block');

      return $blocks;
		case 'view':
			switch ($delta) {

			case '1': 
				// !!! This function keeps breaking thins, content_profile_page_edit
				//	creating hard-to-trace errors possibly at form_alter function
				// Or, block-verdant_share-0.tpl.php  ??  I think it's fixed
				//	with the include this module now starts with. Hopefully?
					$type = 'share_ride';
					global $user;
					$account = $user;
					$blocks['subject'] = t('My RideShare');
					$blocks['content'] =  'Your post will act as your search parameters:' .
						'<div id="verdant_rideshare">' . content_profile_page_edit($type, $account) . '</div>';
					$blocks['visibility'] = 'share/ri*';
					$blocks['pages'] = 2;   // visibility and pages, don;t see docs, trying by hand  // !!! added late, because of spelling error, what's this do? !!!
					//dsm($blocks);
					return $blocks;

				case '2': 
					$type = 'share_flight';
					global $user;
					$account = $user;
					$blocks['subject'] = t("My Flight & Taxi Info");
					$blocks['content'] =  //'Entry form available soon.';

						content_profile_page_edit($type, $account);
					 return $blocks;
			}
  }
}





/* function verdant_carpool_view
 *	We have a default view, pull in the current user's content_profile rideshare
 *	node, and modify the filtered search based on their preferences.
 *		Alternative idea: could simply generate a URL that presets the filters 
 *  !!! I think this would be better done in the view, where users could
 *  intuitively fix it.
 */

function LETTING_THE_VIEW_CREATE_THE_MENUS_verdant_share_menu_NOT_USED() {
	$items = array();

	//Carpool map page
	$items['share/ride/map'] = array(
		'title' => 'Rideshare Map',
		'description' => 'Post, or search the map for a rideshare',
		'page callback' => 'verdant_share_map_page',
		'access arguments' => array('access content'), //!!! reimplement? 
		'type' => MENU_NORMAL_ITEM
	);

	$items['share/ride/chart'] = array(
		'title' => 'Rideshare Chart',
		'description' => 'Post, or use the chart to sort possible rides',
		'page callback' => 'verdant_share_chart_page',  // CHANGE !!!!! :s /map/chart
		'access arguments' => array('access content'), //!!! reimplement? 
		'type' => MENU_NORMAL_ITEM
	); 


	return $items;
}

/******* Views: api, load it, and internal functions to fill exposed forms *******/

/**
 * Implementation of hook_views_api
 */
// This hook simply tells views that this module supports Views API 2
function verdant_share_views_api() {
		return array(
			'api' => 2,
			//'path' => drupal_get_path('module', 'verdant_share') . '/.'; 
					// Don't need if the *inc files are in this directory, they are.
		);
}


/**
 *	verdant_share_date_filter is called from the view, and returns
 *	text for a line of links that simulate filling in the exposed options.
 *
 *	- Note that the exposed options are there, hidden via css, and exposing
 *	them lets you see what is happening.  It should be fine to expose them
 *  if you think that would be a "feature."
 *	- The Date module seems broken for exposed filters.  Search for the word
 *	'horrible' in the text below.  Others seem to be playing with the problems
 *	of exposed filters for date, and I didn't dig deeply, just trying to get
 *	everything in place here for now.
 *	- Timezones hacked, there must be a better way, search for $tz_offset !!!
 *	- Need to code in if the user hasn't entered a date !!!
 *	- Eventually, would like to give the admin more control, or the user,
 *	for example changing the acceptable time window. See MOVE_TO_SETTINGS
 *	- Might also add power-user options, though version has absorbed most of
 *	what I intended to do in power-options
 */
function verdant_share_date_filter() {
	/* Get the user's content_profile for share_ride */
	$type = 'share_ride';
  global $user;
	$ride_share = content_profile_load($type, $user->uid, $lang = '')	;

	// MOVE_TO_SETTINGS
	$timediameter = 4;  /* diameter of window -- hours, intended for text.  Not used yet, is it? */
	$time = 30 * $timediameter; // 1 hour diameter = 30 minute radius
	  /* "radius" in minutes -- they must be leaving within $time minutes of me */


	$date_format_string = "Y-m-d\TH:i:s";  //!!!! not sure what \T is

	//--- ARRIVAL window ---//
	$arrival = $ride_share->field_arrival_time[0]['value'];

	/* warning/help/TO-DO for future:
	 *	Dates are doing very weird things *
	 *  the field_arrival_time doesn't seem to match the date I just entered,
	 *  and then format_date throws it off again, in the same direction (later)
	 *  Found help here, but it looks like a kludge: 
	 *		http://drupal.org/node/355394
	 */
  $tz_offset = strtotime(date("M d Y H:i")) - strtotime(gmdate("M d Y H:i"));
	$arrival_stamp = strtotime( $arrival ) + $tz_offset; 


	// arrive after beginning of window
	$arrival_stamp_early = $arrival_stamp - $time * 60; 
	$arrival_early = date($date_format_string, $arrival_stamp_early);
	$arrival_min_date = date('Y-m-d', $arrival_stamp_early);
	$arrival_min_time = date('H\%3\Ai', $arrival_stamp_early);  // note: put html tranform into date function 16:43 is 16%3A43

	// arrive before late end of window -- DATES IS BROKEN!!!
	// I want to get the rest of the module working, see if dates
	// gets fixed.  I get the sense people are working on this, and
	// have no idea what's wrong... but it seems to require a date to be
	// a day later, rather than an hour later, to be "after"
	$arrival_stamp_late = $arrival_stamp + $time * 60;
	$arrival_late = date($date_format_string, $arrival_stamp_late);
	$arrival_max_date = date('Y-m-d', $arrival_stamp_late + 24 *3600); // horrible!!!
	$arrival_max_time = date('H\%3\Ai', $arrival_stamp_late);  // note: put html tranform into date function 16:43 is 16%3A43 ... probably didn't have to do that,nothing seemed to break.

	// and the fragment of the URL:
	$arrive_fragment = "date_filter_arrive[min][date]=$arrival_min_date&date_filter_arrive[min][time]=$arrival_min_time&date_filter_arrive[max][date]=$arrival_max_date&date_filter_arrive[max][time]=$arrival_max_time";


	
	//---  DEPARTURE window ---//
	$departure = $ride_share->field_departure_time[0]['value'];
	$departure_stamp = strtotime( $departure)  + $tz_offset;

	// depart after beginning of window
	$departure_stamp_early = $departure_stamp - $time * 60; // seems to work ok
	$departure_early = date($date_format_string, $departure_stamp_early);
	$departure_min_date = date('Y-m-d', $departure_stamp_early);
	$departure_min_time = date('H\%3\Ai', $departure_stamp_early);  // :-) note: put html tranform into date function 16:43 is 16%3A43

	// depart before late end of window
	$departure_stamp_late = $departure_stamp + $time * 60 + /* horrible!!! */ + 3600 * 24;
	$departure_late = date($date_format_string, $departure_stamp_late);
	$departure_max_date = date('Y-m-d', $departure_stamp_late);
	$departure_max_time = date('H\%3\Ai', $departure_stamp_late);  // :-) note: put html tranform into date function 16:43 is 16%3A43

	// and the fragment of the URL:
	$depart_fragment = "date_filter_depart[min][date]=$departure_min_date&date_filter_depart[min][time]=$departure_min_time&date_filter_depart[max][date]=$departure_max_date&date_filter_depart[max][time]=$departure_max_time";

	//--- Some basic choice fragments: ---//
	$middlefavorites = "flagged_favorites=All&unflagged_remove=0";
	$favorites = "flagged_favorites=1&unflagged_remove=0";
	$check_removed = "flagged_favorites=All&unflagged_remove=1";
	
	
	//--- Create the links to pass to the view --//
	/* (note: also considered just passing the fragments, so could
		be edited in the view, that is an easy switch to make */
	$l_all = "<a href=\"$base?$middlefavorites\" 
			title=\"All shares except those you have removed\" >Show All</a>";
	$l_arrive = "<a href=\"$base?$middlefavorites&$arrive_fragment\" 
			title=\"See people arriving nearly the same time as you\" >By Arrival -- $timediameter hour window</a>";
	$l_depart = "<a href=\"$base?$middlefavorites&$depart_fragment\" 
			title=\"See people departing nearly the same time as you\" >By Departure  -- $timediameter hour window</a>";
	$l_match = "<a href=\"$base?$middlefavorites&$depart_fragment&$arrive_fragment\" 
			title=\"See people traveling at about the same times as you, both arrival and departure\" >Both Times</a>";
	$l_favs = "<a href=\"$base?$favorites\" 
			title=\"Only see people clicked as favorites\" >Favorites Only</a>";
	$l_removed = "<a href=\"$base?$check_removed\" style=\"font-size: .9em;\"
			title=\"Reconsider posts you've previously removed\" >Reconsider Removed</a>";
	
	$id = "views-exposed-form-verdant-module-generated-rideshare-page-2"; // !!!

	$quicklinks = "$l_all | $l_arrive | $l_depart | $l_match | $l_favs | $l_removed";

	return array($quicklinks);
}
 
 
	// Let users play with this (is that a good idea?)
	// $views[$view->name] = $view;



// Alter the form to point back at same page.
function verdant_share_form_alter(&$form, $form_state, $form_id) {

	if ( $form_id == 'share_ride_node_form') {
		// add some css ... might need this more often?
		drupal_add_css(drupal_get_path('module', 'verdant_share') .'/css/verdant_share_extra_style.css');
		// Redirect
		//not ABSOLUTELY positive this can't be tampered with, 
		//	$form['#redirect'] = $_GET['q']; 
		//	so hard code to be safe
		if ( $_GET['q'] == 'share/ride/map' ) {
			$form['#redirect'] = 'share/ride/map';
		} else {
			$form['#redirect'] = 'share/ride/chart';
		}
		// warning: docs tell admin ok to change these URLS !!!

		// Keep form super-simple	 for users
		
		// Can create these blocks by hand, for now.
		$form['body_field']['body']['#rows'] = 3;
		$form['body_field']['teaser_include']['#access'] = FALSE;
		unset($form['body_field']['format']);
		$form['comment_settings']['#access'] = FALSE;
		$form['menu']['#access'] = FALSE;
		$form['path']['#access'] = false;
		$form['author']['#access'] = false;
		$form['options']['#access'] = false;
		$form['revision_information']['#access'] = false;
		// Want to remove long, lat boxes and some text

		// !!! can this go to inc file?
		$form['locations'][0]['#collapsed'] = 0;

		//dsm($form['locations'] ); 

		// I hate the instructions text.
		// thse people need a better answer: http://drupal.org/node/325820
		// It's set as ['locpick']['instructions'][#value] using html, but not
		//	coming through in dsm above.  Confusing.  Almost as if I get rid
		// 	of it, and it comes back?  Dealt with in css !!!
		// Something seems wrong with locpick

		// This next one does nothing:
		/*
		unset( $form['locations'][0]['#location_settings']['form']['fields']['locpick'] );

		unset($form['body_field']['format']['format']['guidelines']);
		unset($form['attachments']);
		 */
	}
}



					 
/* Views for matching times */
/* http://thedrupalblog.com/passing-date-ranges-view-arguments */
// define the db_rewrite_sql hook:
function NOT_USED_FOR_CARPOOLING_AT_THIS_TIME_HERE_FOR_REFERENCE_FOR_FUTURE_WORK_verdant_share_db_rewrite_sql($query, $primary_table = 'n', $primary_field = 'nid', $args = array()) {
  // search for the view
  if (is_object($args['view']) && $args['view']->name=='flight_connections') {
    // if there are no view arguments, don't bother continuing     
   	if (!is_array($args['view']->args)) return;

		// not sure if above is right... I'm getting no arg as an empty array
		//	which still sets is_array true
		//dsm(count($args['view']->args));
		if (count($args['view']->args) < 1 ) return;

		// the argument indicates which field to operate on, arrive, depart?
		$what = $args['view']->args[0]; // for example, arrival time.
		if ( $what == 'departure' ) {
			$field = 'field_departure_time';
		} elseif ( $what == 'arrival' ) {
			$field = 'field_arrival_time';
		} else {
			return;
		}


		// Find the start and end time for that field, for the current user
		global $user;
		$my_trip = content_profile_load('share_flight', $user->uid);
		//dsm($my_trip->{$field}[0][value]); // example: 2010-02-13 02:00:00
		$date = $my_trip->{$field}[0][value];
		$time = strtotime($date);  // seconds since 1970
		$endDate = date('Y-m-d H:m:s', $time + 7200); // add 2 hours
		$startDate =  date('Y-m-d H:m:s', $time - 7200); // subtract 2 hours
		//dsm(array("plus and minus two hours", $startDate, $endDate));


    // validate dates. exit function if issue -> cataldo: eh. 
							    //if (strlen($startDate) && !checkdate(date('m', strtotime($startDate)), date('d', strtotime($startDate)), date('Y', strtotime($startDate)))) return;
							    //if (strlen($endDate) && !checkdate(date('m', strtotime($endDate)), date('d', strtotime($endDate)), date('Y', strtotime($endDate)))) return;

		// create var for where clause
		$where = "";

		// define table alias
		//$tableAlias = 'node_data_field_departure_time_field_departure_time_value';
		$tableAlias = "content_field_" . $what . "_time";


		$where = " {$tableAlias}.field_$what" . "_time_value >= '$startDate' ";
	 	$where .= " and ";
		$where .= " {$tableAlias}.field_$what" . "_time_value <= '$endDate' ";

		//return array('join' => "inner join {content_type_share_flight} $tableAlias on node.vid = $tableAlias.vid and $where");

		return array('join' => "inner join {content_field_$what" . "_time} $tableAlias on node.vid = $tableAlias.vid and $where");

			

    //return array('join' => "inner join {content_field_$what" . "_time} $tableAlias on node.vid = $tableAlias.vid and $where");
  }

}
/*
Now, you can pass the date ranges in as arguments using the views_embed_view function:
<?php
$viewName = 'MYVIEWNAME';
$arg = array('2008-01-01','2008-12-31');
$viewsHtml = views_embed_view($viewName, 'default', $arg);
?>
 */

